from __future__ import annotations

from typing import Any

from config.settings import AppSettings


def _type_str(field_schema: dict[str, Any]) -> str:
    if "$ref" in field_schema:
        return str(field_schema["$ref"]).rsplit("/", 1)[-1]
    if "anyOf" in field_schema:
        return " | ".join(_type_str(s) for s in field_schema["anyOf"])
    if field_schema.get("type") == "null":
        return "null"
    return str(field_schema.get("type", "any"))


def _render_model(name: str, model_schema: dict[str, Any], lines: list[str]) -> None:
    lines.append(f"## {name}")
    lines.append("")
    required = set(model_schema.get("required", []))
    properties = model_schema.get("properties", {})
    lines.append("| Field | Type | Required | Default | Description |")
    lines.append("|---|---|---|---|---|")
    for field_name, field_schema in properties.items():
        type_str = _type_str(field_schema)
        is_required = "yes" if field_name in required else "no"
        default = field_schema.get("default", "")
        description = field_schema.get("description", "")
        lines.append(
            f"| {field_name} | {type_str} | {is_required} | {default} | {description} |"
        )
    lines.append("")


def render_markdown() -> str:
    schema = AppSettings.model_json_schema()
    defs = schema.get("$defs", {})
    lines: list[str] = [
        "# Configuration Reference",
        "",
        "Auto-generated by `make config-docs`. Do not edit by hand.",
        "",
    ]
    _render_model("AppSettings", schema, lines)
    for def_name, def_schema in defs.items():
        _render_model(def_name, def_schema, lines)
    return "\n".join(lines) + "\n"


def main() -> None:
    print(render_markdown(), end="")


if __name__ == "__main__":
    main()
