"""
Reusable pytest contract test suites for cloud-agnostic ports.
"""

from ports_testing.contracts.lock import (
    LockConfig,
    lock_config,
    test_lock_concurrency_twenty_contenders,
    test_lock_fencing_tokens_are_strictly_monotonic,
    test_lock_renew_successfully_extends_ttl,
    test_lock_stale_lease_release_noop,
    test_lock_ttl_expiration_allows_takeover,
)
from ports_testing.contracts.queue import (
    QueueConfig,
    queue_config,
    test_queue_consumer_group_fanout,
    test_queue_dlq_routing_after_max_retries,
    test_queue_idempotency_deduplication,
    test_queue_nack_redelivery,
    test_queue_nack_without_requeue_routes_to_dlq,
    test_queue_publish_and_consume,
    test_queue_visibility_timeout_redelivery,
)
from ports_testing.contracts.stores import (
    BlobStoreConfig,
    SecretStoreConfig,
    blob_store_config,
    secret_store_config,
    test_audit_sink_append_returns_monotonically_increasing_sequence,
    test_audit_sink_concurrent_appends_have_unique_monotonic_sequences,
    test_audit_sink_payload_immutability_caller_mutation,
    test_blob_store_content_addressing,
    test_blob_store_delete_is_idempotent,
    test_blob_store_get_nonexistent_raises,
    test_blob_store_list_prefix_and_lexicographical_ordering,
    test_blob_store_overwrite,
    test_blob_store_put_and_get,
    test_secret_store_get_existing,
    test_secret_store_get_nonexistent_raises,
)

__all__ = [
    "BlobStoreConfig",
    "LockConfig",
    "QueueConfig",
    "SecretStoreConfig",
    "blob_store_config",
    "lock_config",
    "queue_config",
    "secret_store_config",
    "test_audit_sink_append_returns_monotonically_increasing_sequence",
    "test_audit_sink_concurrent_appends_have_unique_monotonic_sequences",
    "test_audit_sink_payload_immutability_caller_mutation",
    "test_blob_store_content_addressing",
    "test_blob_store_delete_is_idempotent",
    "test_blob_store_get_nonexistent_raises",
    "test_blob_store_list_prefix_and_lexicographical_ordering",
    "test_blob_store_overwrite",
    "test_blob_store_put_and_get",
    "test_lock_concurrency_twenty_contenders",
    "test_lock_fencing_tokens_are_strictly_monotonic",
    "test_lock_renew_successfully_extends_ttl",
    "test_lock_stale_lease_release_noop",
    "test_lock_ttl_expiration_allows_takeover",
    "test_queue_consumer_group_fanout",
    "test_queue_dlq_routing_after_max_retries",
    "test_queue_idempotency_deduplication",
    "test_queue_nack_redelivery",
    "test_queue_nack_without_requeue_routes_to_dlq",
    "test_queue_publish_and_consume",
    "test_queue_visibility_timeout_redelivery",
    "test_secret_store_get_existing",
    "test_secret_store_get_nonexistent_raises",
]
