components:
  accounting:
    envOverrides:
    - name: JAVA_TOOL_OPTIONS
      value: -Xmx300m -Xms300m
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 100Mi
  ad:
    envOverrides:
    - name: JAVA_TOOL_OPTIONS
      value: -Xmx300m -Xms300m
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 100Mi
  agent:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  astronomy-db:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  cart:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  chatbot:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  checkout:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  currency:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  email:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  flagd:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  fraud-detection:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  frontend:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  frontend-proxy:
    ingress:
      enabled: true
      hosts:
      - host: localhost
        paths:
        - path: /
          pathType: Prefix
          port: 8080
      ingressClassName: traefik
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  image-provider:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  kafka:
    envOverrides:
    - name: KAFKA_HEAP_OPTS
      value: -Xmx500m -Xms500m
    resources:
      limits:
        cpu: 300m
        memory: 700Mi
      requests:
        cpu: 50m
        memory: 100Mi
  load-generator:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  mcp:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  opamp-server:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  payment:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  product-catalog:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  quote:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  recommendation:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  shipping:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  telemetry-docs:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
  valkey-cart:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 50Mi
grafana:
  enabled: false
opensearch:
  opensearchJavaOpts: -Xmx512m -Xms512m
  resources:
    limits:
      cpu: 500m
      memory: 700Mi
    requests:
      cpu: 200m
      memory: 512Mi
opentelemetry-collector:
  mode: deployment
  presets:
    clusterMetrics:
      enabled: false
    hostMetrics:
      enabled: false
    kubeletMetrics:
      enabled: false
    kubernetesAttributes:
      enabled: false
prometheus:
  enabled: false
