apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: checkout-evict
  namespace: victim
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app.kubernetes.io/name: checkout
  duration: '90s'
