apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: checkout-latency
  namespace: victim
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app.kubernetes.io/name: checkout
  delay:
    latency: '500ms'
  duration: '90s'
